repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: ./run_pytest.sh
        language: system
        types: [python]
        pass_filenames: false # Run all tests, not just those related to changed files
        always_run: true # Always run tests, even if no Python files changed